name: Sync to xoveexu-com csconfstats branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cs-conf-stats
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout xoveexu-com@csconfstats
        uses: actions/checkout@v4
        with:
          repository: Xovee/xoveexu-com
          ref: csconfstats
          token: ${{ secrets.GH_PAT }}
          path: xoveexu-com

      - name: Sync files
        run: |
          rsync -av --delete \
            --exclude='.git' \
            ./ xoveexu-com/

      - name: Commit & push
        working-directory: xoveexu-com
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          if git diff --cached --quiet; then
            echo "✅ No changes to sync"
            exit 0
          fi
          git commit -m "🔄 Sync from cs-conf-stats @${{ github.sha }}"
          git push origin csconfstats
          