name: Sync to homepage repo

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cs-conf-stats repository
        uses: actions/checkout@v3

      - name: Clone homepage repository
        run: |
          git clone --depth 1 https://xovee:${{ secrets.GH_PAT }}@github.com/Xovee/xoveexu-com.git homepage-temp
          rm -rf homepage-temp/.git

      - name: Create/Checkout csconfstats branch in hompage
        run: |
          cd homepage-temp
          git init
          git remote add origin https://xovee:${{ secrets.GH_PAT }}@github.com/Xovee/xoveexu-com.git
          git fetch origin csconfstats || true
          git checkout -B csconfstats

      - name: Copy files from csconfstats to homepage
        run: |
          sleep 5
          rsync -av --delete --ignore-missing-args ".git/" ./ homepage-temp/ || true

      - name: Commit and Push Changes
        run: |
          cd homepage-temp
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync content from cs-conf-stats"
            git push -f origin csconfstats
          fi
