name: Sync to xoveexu-com csconfstats branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cs-conf-stats
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push changes to xoveexu-com csconfstats branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git clone --branch csconfstats https://github.com/Xovee/xoveexu-com.git target-repo
          rsync -av --delete --exclude='.git' ./ target-repo/
          
          cd target-repo
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync from cs-conf-stats main"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Xovee/xoveexu-com.git csconfstats
          fi
